(()=>{
'use strict';
const K='wwtrGardenV2',C=6,R=5,N=C*R;
const P={
 tomato:{n:'Tomato',o:'Human archive',a:'tomato',m:[42,72],u:10,g:[1,1,2,2],s:['Seed','Hooked sprout','Two-leaf seedling','Leafing plant','Fruit-bearing plant']},
 newPine:{n:'New Pine',o:'Human archive',a:'pine',m:[35,66],u:8,g:[1,2,2,3],s:['Seed','Green spike','Tiny sapling','Young pine','Established pine']},
 nitrogenFern:{n:'Nitrogen Fern',o:'Human archive',a:'fern',m:[48,78],u:11,g:[1,1,2,2],s:['Spore seed','Fiddlehead','First frond','Layered fern','Full fern']},
 climbingMoss:{n:'Climbing Moss',o:'Human archive',a:'moss',m:[55,86],u:9,g:[1,1,2,2],s:['Resting spores','First green','Creeping patch','Climbing mat','Established moss']},
 groundVine:{n:'Vaeren Ground Vine',o:'Vaeren nursery',a:'vine',m:[28,62],u:7,g:[1,1,2,2],s:['Seed','Folded shoot','First tendril','Branching vine','Established ground vine']},
 silverBark:{n:'Silver-bark',o:'Vaeren nursery',a:'silver',m:[32,66],u:8,g:[1,2,2,3],s:['Seed','Pale shoot','Slim sapling','Young silver-bark','Established silver-bark']}
};
const D={
 irrigationAccommodation:['Accommodation, not competition','Near a tomato bed, the Vaeren ground vine folds its roots away while human irrigation is active, then extends again after the excess drains.'],
 rootAccommodation:['Roots can make room','New Pine and silver-bark alter their root paths around one another. Neither grafts. Neither retreats entirely.'],
 encouragement:['An unofficial variable','The climbing moss has responded to repeated attention. Karu would have called encouragement a measurable growing condition.'],
 mixedNursery:['Neither knowledge alone','A healthy human plant and a healthy Vaeren plant have matured within the same nursery. The garden works because both bodies of knowledge remain present.'],
 restraint:['Not every imbalance needs intervention','A healthy plant was left alone long enough to keep growing without help. Listening can include deciding not to interfere.']
};
const q=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const E={grid:q('garden-grid'),seeds:q('seed-list'),seedName:q('selected-seed-name'),cycle:q('cycle-number'),rCard:q('resonance-card'),rTitle:q('resonance-title'),rCopy:q('resonance-copy'),rLight:q('resonance-light'),obs:q('observation-text'),disc:q('discoveries'),save:q('save-state'),next:q('advance-cycle'),reset:q('reset-garden'),dialog:q('reset-dialog'),seedSection:q('seed-section')};
const S={cycle:1,tool:'plant',seed:'tomato',plots:[],disc:new Set(),obs:'',timer:null};
const empty=i=>({i,p:null,st:0,x:0,w:44,h:100,l:0,unt:0,last:0});
function init(){S.plots=Array.from({length:N},(_,i)=>empty(i));}
function load(){init();try{const z=JSON.parse(localStorage.getItem(K));if(!z||!Array.isArray(z.plots))return;S.cycle=+z.cycle||1;S.tool=['plant','water','listen','lift'].includes(z.tool)?z.tool:'plant';S.seed=P[z.seed]?z.seed:'tomato';S.disc=new Set(z.disc||[]);S.plots=Array.from({length:N},(_,i)=>{const a=z.plots[i];if(!a||!P[a.p])return empty(i);return {...empty(i),...a,i,st:clamp(+a.st||0,0,4),x:Math.max(0,+a.x||0),w:clamp(+a.w||44,0,100),h:clamp(+a.h||100,0,100)}})}catch(e){init()}}
function save(){localStorage.setItem(K,JSON.stringify({cycle:S.cycle,tool:S.tool,seed:S.seed,plots:S.plots,disc:[...S.disc]}));clearTimeout(S.timer);E.save.textContent='Saved';E.save.classList.add('is-saving');S.timer=setTimeout(()=>{E.save.textContent='Saved on this device';E.save.classList.remove('is-saving')},700)}
function nb(i){const r=Math.floor(i/C),c=i%C,a=[];for(let y=-1;y<=1;y++)for(let x=-1;x<=1;x++){if(!x&&!y)continue;const rr=r+y,cc=c+x;if(rr>=0&&rr<R&&cc>=0&&cc<C)a.push(S.plots[rr*C+cc])}return a}
const near=(p,id)=>nb(p.i).some(x=>x.p===id);
function wet(p,t){const[a,b]=t.m;return p.w<a-15?'parched':p.w<a?'dry':p.w<=b?'ideal':p.w<=b+14?'damp':'waterlogged'}
function health(p,t){const m=wet(p,t);p.h=clamp(p.h+(m==='ideal'?5:m==='dry'||m==='damp'?-2:m==='parched'?-12:-10),0,100)}
function bonus(p){return(p.p==='groundVine'&&near(p,'tomato'))||(p.p==='tomato'&&near(p,'groundVine'))||(p.p==='newPine'&&near(p,'silverBark'))||(p.p==='silverBark'&&near(p,'newPine'))||(p.p==='climbingMoss'&&p.l>=2)?1:0}
function quality(p,t){const m=wet(p,t);return m==='ideal'&&p.h>=75?2:(m==='dry'||m==='damp')&&p.h>=55?1:0}
function observe(s){S.obs=s;E.obs.textContent=s}
function discover(id){if(S.disc.has(id))return;S.disc.add(id);observe(`New observation: ${D[id][0]}. ${D[id][1]}`)}
function discoveries(){S.plots.forEach(p=>{if(!p.p)return;if((p.p==='groundVine'&&near(p,'tomato'))||(p.p==='tomato'&&near(p,'groundVine')))discover('irrigationAccommodation');if((p.p==='newPine'&&near(p,'silverBark'))||(p.p==='silverBark'&&near(p,'newPine')))discover('rootAccommodation');if(p.p==='climbingMoss'&&p.l>=3&&p.st>=2)discover('encouragement');if(p.unt>=2&&p.h>=75&&p.st>=2)discover('restraint')});const h=S.plots.some(p=>p.st>=3&&['tomato','newPine','nitrogenFern','climbingMoss'].includes(p.p)&&p.h>=65),v=S.plots.some(p=>p.st>=3&&['groundVine','silverBark'].includes(p.p)&&p.h>=65);if(h&&v)discover('mixedNursery')}
function next(){S.cycle++;const a=[];S.plots.forEach(p=>{if(!p.p){p.w=clamp(p.w-4,8,100);return}const t=P[p.p];p.w=clamp(p.w-t.u,0,100);health(p,t);p.unt=p.last<S.cycle-1?p.unt+1:0;if(p.st<4){p.x+=quality(p,t)+bonus(p);const need=t.g[p.st]||2;if(p.x>=need){p.x=0;p.st++;p.h=clamp(p.h+4,0,100);a.push(`${t.n}: ${t.s[p.st]}`)}}});discoveries();observe(a.length?`${a.slice(0,3).join(' · ')}. The nursery has changed.`:S.plots.some(p=>p.p&&p.h<50)?'A cycle passes without new growth. Something is spending its energy on survival instead.':'A cycle passes. Not every change reaches the surface at once.');render();save()}
function plant(p){if(p.p)return observe('Something is already growing here. Lift it first if you want to change the bed.');p.p=S.seed;p.st=0;p.x=0;p.h=100;p.w=clamp(p.w,38,58);p.l=0;p.unt=0;p.last=S.cycle;observe(`${P[p.p].n} seed placed. Nothing green appears yet. The first task is simply to keep the conditions possible.`)}
function water(p){p.w=clamp(p.w+28,0,100);p.last=S.cycle;p.unt=0;if(!p.p)return observe('Water darkens the empty soil. It will hold the change for a while.');const t=P[p.p],m=wet(p,t);observe(m==='waterlogged'?`${t.n}: the soil is holding more water than the roots can comfortably use.`:m==='damp'?`${t.n}: moisture gathers around the roots. Enough, probably.`:`${t.n}: the soil accepts the water without strain.`)}
function listen(p){if(!p.p)return observe('Bare soil answers mostly with temperature, moisture and the small fact that it is not inert.');const t=P[p.p];p.l++;p.last=S.cycle;p.unt=0;if(p.p==='climbingMoss'&&p.l>=2)p.h=clamp(p.h+3,0,100);const m=wet(p,t),h=p.h>=80?'Its living pattern feels steady.':p.h>=55?'There is strain, but not collapse.':'The dissonance is difficult to miss.',w={parched:'The root zone is sharply dry.',dry:'The root zone is beginning to ask for water.',ideal:'Moisture sits where this plant can use it.',damp:'There is more water than necessary, but the roots are coping.',waterlogged:'Water is crowding the spaces the roots need.'}[m];observe(`${t.n}, ${t.s[p.st].toLowerCase()}. ${h} ${w}`)}
function lift(p){if(!p.p)return observe('There is nothing here to lift.');const n=P[p.p].n,w=p.w;Object.assign(p,empty(p.i),{w:clamp(w,18,70)});observe(`${n} lifted from the bed. The soil keeps the shape of the roots for a little while.`)}
function act(i){const p=S.plots[i];({plant,water,listen,lift}[S.tool])(p);discoveries();render();save()}
function tool(t){S.tool=t;document.querySelectorAll('.tool-button').forEach(b=>{const a=b.dataset.tool===t;b.classList.toggle('is-active',a);b.setAttribute('aria-pressed',a)});E.seedSection.classList.toggle('is-muted',t!=='plant');save()}
function seed(id){if(!P[id])return;S.seed=id;E.seedName.textContent=P[id].n;document.querySelectorAll('.seed-choice').forEach(b=>{const a=b.dataset.seed===id;b.classList.toggle('is-active',a);b.setAttribute('aria-selected',a)});if(S.tool!=='plant')tool('plant');save()}
function seedUI(){E.seeds.innerHTML=Object.entries(P).map(([id,t])=>`<button class="seed-choice ${id===S.seed?'is-active':''}" data-seed="${id}" role="option" aria-selected="${id===S.seed}"><span class="seed-swatch sw-${t.a}" aria-hidden="true"></span><span><strong>${t.n}</strong><small>${t.o}</small></span></button>`).join('');E.seeds.querySelectorAll('.seed-choice').forEach(b=>b.onclick=()=>seed(b.dataset.seed));E.seedName.textContent=P[S.seed].n}
function art(t,st){return`<span class="plant-art art-${t.a} stage-${st}" aria-hidden="true"><i></i><b></b><em></em><u></u><s></s></span>`}
function garden(){E.grid.innerHTML=S.plots.map(p=>{if(!p.p)return`<button class="plot is-empty" data-i="${p.i}" style="--wet:${p.w}" aria-label="Plot ${p.i+1}, empty soil"><span class="soil"></span><span class="empty-ring"></span></button>`;const t=P[p.p],m=wet(p,t),hc=p.h<40?'is-struggling':p.h<65?'is-stressed':'is-healthy';return`<button class="plot has-plant ${hc} moisture-${m}" data-i="${p.i}" style="--wet:${p.w};--health:${p.h}" aria-label="Plot ${p.i+1}, ${t.n}, ${t.s[p.st]}"><span class="soil"></span>${art(t,p.st)}<span class="plot-caption"><strong>${t.n}</strong><small>${t.s[p.st]}</small></span></button>`}).join('');E.grid.querySelectorAll('.plot').forEach(b=>b.onclick=()=>act(+b.dataset.i))}
function discUI(){E.disc.innerHTML=Object.entries(D).map(([id,d])=>{const a=S.disc.has(id);return`<article class="discovery ${a?'is-unlocked':'is-locked'}"><span>${a?'✦':'·'}</span><div><h3>${a?d[0]:'Observation not yet made'}</h3><p>${a?d[1]:'The nursery has more to teach you.'}</p></div></article>`}).join('')}
function resonance(){const a=S.plots.filter(p=>p.p);if(!a.length)return[0,'The garden is listening.','Nothing has taken root yet. The soil is quiet, not empty.'];let sc=0;a.forEach(p=>{const t=P[p.p];sc+=p.h*.55+p.st*7+(wet(p,t)==='ideal'?12:0)+(p.h<40?-22:0)+((p.p==='groundVine'&&near(p,'tomato'))?12:0)+((p.p==='newPine'&&near(p,'silverBark'))?12:0)+((p.p==='climbingMoss'&&p.l>=2)?5:0)});sc/=a.length;return sc<35?[1,'The pattern is strained.','Several living things are spending more energy enduring the nursery than growing within it.']:sc<55?[2,'The garden has not settled.','There are answers here, but they do not yet agree.']:sc<72?[3,'Something is beginning to answer.','Roots are finding workable paths. The nursery still asks for attention, but not constant correction.']:sc<88?[4,'The garden feels balanced.','No single plant defines the pattern. Each is changing the space around it and being changed in return.']:[5,'The nursery is in Resonance.','Growth, restraint and accommodation have become part of the same living pattern.']}
function render(){E.cycle.textContent=S.cycle;garden();discUI();const r=resonance();E.rCard.dataset.level=r[0];E.rTitle.textContent=r[1];E.rCopy.textContent=r[2];E.rLight.style.setProperty('--resonance-level',r[0]);document.body.dataset.resonance=r[0];if(S.obs)E.obs.textContent=S.obs}
function reset(){localStorage.removeItem(K);S.cycle=1;S.tool='plant';S.seed='tomato';S.disc=new Set();S.obs='The beds have been cleared. Choose a seed and begin again; nothing green should appear until the seed has had time to become it.';init();seedUI();tool('plant');render();save()}
document.querySelectorAll('.tool-button').forEach(b=>b.onclick=()=>tool(b.dataset.tool));E.next.onclick=next;E.reset.onclick=()=>typeof E.dialog.showModal==='function'?E.dialog.showModal():confirm('Clear this saved garden?')&&reset();E.dialog.onclose=()=>{if(E.dialog.returnValue==='confirm')reset()};load();seedUI();tool(S.tool);render();
})();
